src/Entity/Abonne.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AbonneRepository")
 * @UniqueEntity(fields={"prenom"}, message="Ce prénom est déjà utilisé")
 */
class Abonne implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Emprunt", mappedBy="abonne", orphanRemoval=true)
     */
    private $emprunts;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->prenom;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Emprunt[]
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts[] = $emprunt;
            $emprunt->setAbonne($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->contains($emprunt)) {
            $this->emprunts->removeElement($emprunt);
            // set the owning side to null (unless already changed)
            if ($emprunt->getAbonne() === $this) {
                $emprunt->setAbonne(null);
            }
        }

        return $this;
    }
}

src/Entity/Emprunt.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmpruntRepository")
 */
class Emprunt
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_sortie;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_rendu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Livre", inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Abonne", inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonne;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getDateRendu(): ?\DateTimeInterface
    {
        return $this->date_rendu;
    }

    public function setDateRendu(?\DateTimeInterface $date_rendu): self
    {
        $this->date_rendu = $date_rendu;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): self
    {
        $this->abonne = $abonne;

        return $this;
    }
}

src/Form/AbonneType.php
<?php

namespace App\Form;

use App\Entity\Abonne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints;

class AbonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom',TextType::class)
            ->add('roles', ChoiceType::class, [
                'choices' => ['abonne' => 'ROLE_USER',
                             'bibliothécaire' => 'ROLE_ADMIN',
                ],
                'multiple' => true,
                'label' => 'Rôle'
            ])
            ->add('password',PasswordType::class, [
                'mapped' => false,
                'constraints' => [
                    new Constraints\Length([
                        'min' => 6,
                        'minMessage' => "Le mot de passe doit contenir au moins {{ limit }} caractères",
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Abonne::class,
        ]);
    }
}

src/Controller/AbonneController.php
<?php

namespace App\Controller;

use App\Entity\Abonne;
use App\Entity\Emprunt;
use App\Entity\Livre;
use App\Form\AbonneType;
use App\Form\FormLivreType;
use App\Repository\AbonneRepository;
use App\Repository\EmpruntRepository;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;




class AbonneController extends AbstractController
{
    /**
     * @Route("/abonne", name="abonne_index", methods={"GET"})
     */
    public function index(AbonneRepository $abonneRepository): Response
    {
        return $this->render('abonne/index.html.twig', [
            'abonnes' => $abonneRepository->findAll(),
        ]);
    }

    /**
     * @Route("/abonne/nouveau", name="abonne_new", methods={"GET","POST"})
     */
    public function new(UserPasswordEncoderInterface $passwordEncoder, Request $request): Response
    {
        $abonne = new Abonne();
        $form = $this->createForm(AbonneType::class, $abonne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $abonne->setPassword(
                $passwordEncoder->encodePassword(
                    $abonne,
                    $form->get('password')->getData()
                )
            );
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($abonne);
            $entityManager->flush();

            return $this->redirectToRoute('abonne_index');
        }

        return $this->render('abonne/new.html.twig', [
            'abonne' => $abonne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/abonne/{id}", name="abonne_show", methods={"GET"})
     */
    public function show(Abonne $abonne): Response
    {
        return $this->render('abonne/show.html.twig', [
            'abonne' => $abonne,
        ]);
    }

    /**
     * @Route("/abonne/{id}/modifier", name="abonne_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Abonne $abonne): Response
    {
        $form = $this->createForm(AbonneType::class, $abonne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('abonne_index');
        }

        return $this->render('abonne/edit.html.twig', [
            'abonne' => $abonne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/abonne/{id}", name="abonne_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Abonne $abonne): Response
    {
        if ($this->isCsrfTokenValid('delete' . $abonne->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($abonne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('abonne_index');
    }

    /**
     * @Route("/profil", name="profil", methods={"GET"})
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    public function profil(): Response
    {

        return $this->render('abonne/profil.html.twig', []);
    }
    /**
     * @Route("/profil/reserver", name="reserver", methods={"GET","POST"})
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    public function reserver(LivreRepository $livreRepository, EmpruntRepository $empruntRepository, Request $request, EntityManagerInterface $manager): Response
    {
        $liste_livres = $livreRepository->findAll();
        $empruntLivreNonRendus = $empruntRepository->findByNonEmprunte();
        $livresRendu = [];

        // On va parcourir la liste de tous les livres.  
        //Pour chaque livre, on va chercher à savoir s'il fait partie des livres non rendus.
        //Si il ne fait pas partie des livres non rendus, je l'ajoute à l'array $livreRendu

        // On parcourt tous les livres de la bibliothèque
        foreach ($liste_livres as $livre) {
            // je crée une variable booléenne qui sera vrai si le livre actuel est non rendus
            $nonRendu = false;


            //POur chaque livre, on parcourt les livres non rendus
            foreach ($empruntLivreNonRendus as $emprunt) {
                //On compare le livre actuel avec le livreNonRendu
                if ($livre->getId() == $emprunt->getLivre()->getId()) {
                    //Si l'id du livre est égale à l'id livre non rendu, alors $nonRendu est vrai
                    $nonRendu = true;
                }
            }

            //Si $nonRendu est faux, on ajoute le livre à l'array des livres rendus
            if (!$nonRendu) {
                $livresRendu[] = $livre;
            }
        }

        //isMethod() permet de savoir si ma requete HTTP est en GET ou en POST
        if ($request->isMethod("POST")) {
            // La propriété request de l'objet $request permet de récupérer ce qu'il y a dans $_POST
            $liste_livres = $request->get("liste_livres");
            if ($liste_livres) {
                foreach ($liste_livres as $id_livre) {
                    $emprunt = new Emprunt;
                    $emprunt->setAbonne($this->getUser());
                    $emprunt->setLivre($livreRepository->find($id_livre));
                    $emprunt->setDateSortie(new \DateTime('now'));
                    $manager->persist($emprunt);
                }
                $manager->flush();
                return $this->redirectToRoute('profil');
            }
        }
        return $this->render('abonne/reservation.html.twig', [
            'livresRendu' => $livresRendu
        ]);
    }
    /**
     * @Route("profil/ajouter-livre", name="livre_ajouter", methods={"GET","POST"})
     */
    public function ajouterLivre(LivreRepository $livreRepository, EntityManagerInterface $manager,  Request $request)
    {
        $nouveauLivre = new Livre;
        $formAjouter = $this->createForm(FormLivreType::class, $nouveauLivre);
        $formAjouter->handleRequest($request);
        if ($formAjouter->isSubmitted()) {
            if ($formAjouter->isValid()) {
                $manager->persist($nouveauLivre);
                $manager->flush();


                $this->addFlash('success', '<i>' . $nouveauLivre->getTitre() . ' </i> a été ajouté');
                return $this->redirectToRoute('acceuil');
            } else {
                $this->addFlash('warning', 'Le formulaire n\'est pas valide');
            }
        }
        $formAjouter = $formAjouter->createView();
        return $this->render('livre/form_ajouter.html.twig', [
            'formAjouter' => $formAjouter
        ]);
    }
}

templates/abonne/_delete_form.html.twig
<form method="post" action="{{ path('abonne_delete', {'id': abonne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ abonne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/abonne/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/abonne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Abonne{% endblock %}

{% block body %}
    <h1>Edit Abonne</h1>

    {{ include('abonne/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('abonne_index') }}">back to list</a>

    {{ include('abonne/_delete_form.html.twig') }}
{% endblock %}

templates/abonne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abonnés{% endblock %}

{% block body %}
    <h1>Liste des abonné(e)s : {{ abonnes|length }} abonné(es) </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prenom</th>
                <th>Roles</th>
                <th>Password</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for abonne in abonnes %}
            <tr>
                <td>{{ abonne.id }}</td>
                <td>{{ abonne.prenom }}</td>
                <td>{{ abonne.roles ? abonne.roles|json_encode : '' }}</td>
                <td>{{ abonne.password }}</td>
                <td>
                    <a href="{{ path('abonne_show', {'id': abonne.id}) }}">show</a>
                    <a href="{{ path('abonne_edit', {'id': abonne.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('abonne_new') }}">Create new</a>
{% endblock %}

templates/abonne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Abonne{% endblock %}

{% block body %}
    <h1>Create new Abonne</h1>

    {{ include('abonne/_form.html.twig') }}

    <a href="{{ path('abonne_index') }}">back to list</a>
{% endblock %}

templates/abonne/profil.html.twig
{% extends "base.html.twig" %}

{% block title %}Profil{% endblock %}

{% block body %}
<h1>Mon profil</h1>

<table class="table table-responsive">
    <tbody>
        <tr>
            <th>Prénom</th>
            <td>{{ app.user.username }}</td>
        </tr>
    </tbody>
    <div>
        <a href="{{ path('reserver') }}">Emprunter</a>
    </div>
    <div>
        <a href="{{ path('livre_ajouter') }}">
            <i class="fa fa-plus"></i> 
            Ajouter un livre
        </a>
    </div>
    <div>
        <h2>Nombre d'emprunt(s): {{ app.user.emprunts |length }}</h2>
        <table class="table table-responsive">
            <thead class="thead-dark">
                <th>Livre</th>
                <th>Date de Sortie</th>
                <th>Date de rendu</th>
            </thead>
            {% for emprunt in app.user.emprunts %}
            <tr>
                <td>{{ emprunt.livre.titre ~ ' - ' ~  emprunt.livre.auteur  }}</td>
                <td>{{ emprunt.dateSortie ? emprunt.dateSortie|date('Y-m-d') : '' }}</td>
                <td>{{ emprunt.dateRendu ? emprunt.dateRendu|date('Y-m-d') : '' }}</td>
            </tr>
            {% endfor %}
        </table>
        <a href="">Modifier</a>
</table>


{% endblock %}

templates/abonne/reservation.html.twig
{% extends "base.html.twig" %}

{% block title %}Réservation{% endblock %}

{% block body %}
<form action="" method="POST">
    <div class="form-group">
        <label for="">Livres disponibles</label>
        <select multiple class="form-control" name="liste_livres[]">
            {% for livre in livresRendu %}
            <option value="{{ livre.id }}">{{ livre.titre ~ ' - ' ~ livre.auteur }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Emprunter</button>
</form>
{% endblock %}

templates/abonne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abonne{% endblock %}

{% block body %}
    <h1>Abonne</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ abonne.id }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ abonne.prenom }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ abonne.roles ? abonne.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ abonne.password }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('abonne_index') }}">back to list</a>

    <a href="{{ path('abonne_edit', {'id': abonne.id}) }}">edit</a>

    {{ include('abonne/_delete_form.html.twig') }}
{% endblock %}